[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
commands = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir -r backend/requirements.txt"
]

[start]
cmd = "python backend/app.py"
